D2.0p3.6
GreatDevelopers/LibreHatti pull request #533
Opened 2020-05-10 21:42 UTC by lakshaychopra

Updated Dockerfile and docker-compose.yml files.
settings.py file is updates to run in dockerised environment.
Added missing requirements in requirements.txt file.

2020-05-10 22:04 UTC, jasvir99 requested changes

2020-05-10 22:04 UTC, jasvir99 commented on src/librehatti/settings.py
> +        "NAME": "librehatti",
Please use env file to define such information. Create file for dev, qa and prod

2020-05-12 20:27 UTC, jasvir99 commented
@lakshaychopra Please rebase your branch.

2020-05-13 08:55 UTC, lakshaychopra commented
On Wed, May 13, 2020 at 1:57 AM Jasvir Singh Grewal <
notifications@github.com> wrote:

> @lakshaychopra <https://github.com/lakshaychopra> Please rebase your
> branch.
>
Okay


-- 
Lakshay Chopra
Blog- codedynamo.wordpress.com

2020-05-13 16:09 UTC, lakshaychopra commented
> @lakshaychopra Please rebase your branch.

Getting conflicts in rebasing the branch.
Should I skip those commits showing conflicts.

2020-05-13 16:58 UTC, jasvir99 commented
@lakshaychopra  You have to fix the conflicts

2020-05-13 19:28 UTC, lakshaychopra commented
> @lakshaychopra You have to fix the conflicts

@jasvir99 i have rebased my master branch.

2020-05-13 19:40 UTC, jasvir99 commented
@lakshaychopra You have to fix pre-commits checks also. Please refer https://github.com/GreatDevelopers/LibreHatti#raising-pull-request

2020-05-13 19:41 UTC, jasvir99 commented
Also, I don't see the description and title updated.

2020-05-15 15:45 UTC, jasvir99 commented
I'll update it by myself. Thanks for your help. I am closing this PR.

2020-05-15 15:45 UTC, closed without merging